name: SFVRCC
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75145
title: San Francisco Virtual Reality Creative Community
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fd4d58'
    - '#3d2c37'
    - '#1ae1f6'
    - '#ffffff'
    - '#91818c'
  brandStrength: 0.75
  lightness: 0.293492725584656
  saturation: 0.6036966643296182
  rhythmicContrast: 0.6202543596737087
purpose: []
